apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-singers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-singers
  template:
    metadata:
      labels:
        app: app-singers
    spec:
      containers:
        - name: app-singers
          image:  lrsuniga/app-singers
          ports:
            - containerPort: 9090
          livenessProbe:
            httpGet:
              port: 9090
              path: /q/health/live
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: app-singers-service
spec:
  type: ClusterIP
  selector:
    app: app-singers
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090